name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
   workflow_dispatch:
   push:
     branches:
     - main

permissions:
  contents: read
  id-token: write    

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      - name: Execução do comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln

  release:
    name: Criação de Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4

      - name: Autenticando no Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          token_format: 'access_token'
          project_id: ${{ vars.PROJECT_ID }}
          service_account: ${{ vars.SERVICE_ACCOUNT_ID }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_ID }}

      - name: Login no Artifact Registry (Docker)
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          push: true
          tags: |
            ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:latest
            ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:v${{ github.run_number }}
